[package]
name = "timeline_plugin_web_client"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
client_api = { path = "../../../client_api/" }
leptos = "0.6.14"
serde = "1.0.215"
